[package]
name = "databrain-connector-postgres"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
async-trait = "0.1.92"
databrain-auth = { version = "0.1.0", path = "../../auth" }
databrain-connector-core = { version = "0.1.0", path = "../../connector-core" }
futures = "0.3.34"
native-tls = "0.2.18"
postgres-native-tls = "0.5.3"
secrecy = "0.10.3"
tokio = { version = "1.53.1", features = ["rt", "sync", "macros", "time"] }
tokio-postgres = { version = "0.7.18", features = ["with-serde_json-1"] }
tokio-util = "0.7.19"

[dev-dependencies]
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
